[workspace]
resolver = "2"
members = [
    "triton-grpc-client",
]

[workspace.dependencies]
prost = { version = "0.14.1" }
tonic = { version = "0.14.2", features = ["gzip"] }
tonic-prost = { version = "0.14.2" }
tonic-prost-build = { version = "0.14.2" }