[package]
name = "triton-ng"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = { workspace = true }
byteorder = { workspace = true }
crossbeam = { workspace = true }
triton-sys = { workspace = true }
